# Generated by Django 4.0.5 on 2022-10-27 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_book_event_alter_event_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_post_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers_of_seats', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('participint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
