# Generated by Django 4.0.5 on 2022-10-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bookevent_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='numbers_of_seats',
            field=models.PositiveIntegerField(),
        ),
    ]
