# Generated by Django 4.1.2 on 2022-10-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book_event",
            fields=[
                ("bid", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("mobile", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("image", models.ImageField(default="", upload_to="")),
                ("organiser", models.CharField(max_length=150)),
                ("available_seats", models.IntegerField()),
                ("booked_seats", models.IntegerField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
