# Generated by Django 4.0.5 on 2022-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_available_seats_alter_event_booked_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Wedding', 'Wedding'), ('Meeting', 'Meeting'), ('SP', 'Small Party'), ('Bp', 'Big Part')], max_length=150),
        ),
    ]
