# Generated by Django 4.1.2 on 2022-10-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
